project: universe
lastuploaded: "2022-05-03T15:45:55+02:00"
functions:
  create-data:
    id: 007385c6-4a8a-43e5-8db5-b68307ca98f6
    name: create-data
    checksum: e7d3c6a34c7cf80f0b3288fce765d6b08e7293a0dca1ff5dd25aabbcaed9de28
  delete-data:
    id: c9e01647-5424-4084-8433-45e476ddd478
    name: delete-data
    checksum: 5b0268958e237bbc322ac3f69d6b37954b9861d0203e4aa8de94445ba6b43cf0
  list-data:
    id: b62782cc-d4c7-41fc-b72d-d8cf2d07d2c6
    name: list-data
    checksum: 170dcdf029566f6db8df4da5f56f7a3a6a5ce2d3a2a14b112fb63d60f7b61430
  read-data:
    id: 2deacfb6-f8fc-4dc1-adbd-0a4255d52222
    name: read-data
    checksum: e99829648a84a08daecbc5631e7b2d3dcc77fa955b090740f16ff13232093ae2
  update-data:
    id: 9db3d7a4-12c5-4278-8cfe-443083ec2b41
    name: update-data
    checksum: 173b4fb387943fe1d4a7bb1f93a18cb1c4408c8266d9ef96d1395a047fce4d34
gateways:
  data-gateway:
    id: 89f80652-601c-4517-945c-aa7b797d47c2
    name: data-gateway
    short: wNYJTOjWJQ
    routes:
    - function: create-data
      method: POST
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data
    - function: read-data
      method: GET
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data/#{id}
    - function: update-data
      method: PUT
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data/#{id}
    - function: delete-data
      method: DELETE
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data/#{id}
    - function: list-data
      method: GET
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data
