project: universe
lastuploaded: "2022-05-04T18:11:21+02:00"
functions:
  create-data:
    id: 007385c6-4a8a-43e5-8db5-b68307ca98f6
    name: create-data
    checksum: eaad9838cbc738adb1c19a25e1549232bb5be22b4cf6094f8a0a3f33717fd14c
  delete-data:
    id: c9e01647-5424-4084-8433-45e476ddd478
    name: delete-data
    checksum: 92568b5b726eb329abc8ddf76d3b0a46c78a5a68014458b41ffbab2cd8db5404
  list-data:
    id: b62782cc-d4c7-41fc-b72d-d8cf2d07d2c6
    name: list-data
    checksum: 2859062017c6208729eba54a75d4e6f89e3a1efbbd104b64cd6c12dfe6bc7e63
  read-data:
    id: 2deacfb6-f8fc-4dc1-adbd-0a4255d52222
    name: read-data
    checksum: b9f8603911d186d77924db5e94f305bca36e311ac8b01e49c8c41aca6add407d
  update-data:
    id: 9db3d7a4-12c5-4278-8cfe-443083ec2b41
    name: update-data
    checksum: c3976e3996eab330b4bdb24e17c3fa6107b07f9abe519e70cf81ffb8379632a9
gateways:
  data-gateway:
    id: 89f80652-601c-4517-945c-aa7b797d47c2
    name: data-gateway
    short: wNYJTOjWJQ
    routes:
    - function: create-data
      method: POST
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data
    - function: read-data
      method: GET
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data/#{id}
    - function: update-data
      method: PUT
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data/#{id}
    - function: delete-data
      method: DELETE
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data/#{id}
    - function: list-data
      method: GET
      path: https://apigw-dev.heeser.io/v1/gateways/v1/wNYJTOjWJQ/data
